apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: taxi-cicd
spec:
  podTemplate: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: github-push-binding
      interceptors:
        - github:
            secretRef:
              secretKey: webhook-secret-key
              secretName: gitops-webhook-secret
        - cel:
            filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'pixeljonas/taxi-gitops')
            overlays:
              - expression: body.ref.split('/')[2]
                key: ref
      name: ci-dryrun-from-push
      template:
        name: ci-dryrun-from-push-template
    - bindings:
        - ref: taxi-dev-app-taxi-taxi-binding
        - ref: github-push-binding
      interceptors:
        - github:
            secretRef:
              secretKey: webhook-secret-key
              secretName: webhook-secret-taxi-dev-taxi
        - cel:
            filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'pixeljonas/taxi')
            overlays:
              - expression: body.ref.split('/')[2]
                key: ref
      name: app-ci-build-from-push-taxi
      template:
        name: app-ci-template
status:
  configuration:
    generatedName: ""
