apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/pixeljonas/taxi-gitops.git?ref=main
  creationTimestamp: null
  name: taxi-dev
spec: {}
status: {}
