apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: taxi-gitops
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "https://github.com/PixelJonas/taxi-gitops"
    - "https://github.com/PixelJonas/taxi"
