apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: taxi-dev-env
  namespace: openshift-gitops
spec:
  destination:
    namespace: taxi-dev
    server: https://kubernetes.default.svc
  project: taxi-gitops
  source:
    path: environments/taxi-dev/env/overlays
    repoURL: https://github.com/pixeljonas/taxi-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
